// <auto-generated />
namespace Team8ADProjectSSIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class snapshot8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(snapshot8));
        
        string IMigrationMetadata.Id
        {
            get { return "202001211110539_snapshot8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
